name: uniapp
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  google_fonts:
  lottie:
  http:
  supabase_flutter: ^2.9.1
  deepgram_speech_to_text: ^4.0.0
  smooth_page_indicator: ^1.2.1
  flutter_animate: ^4.5.2
  syncfusion_flutter_charts: ^30.1.41
  modal_progress_hud_nsn: ^0.5.1
  record: ^6.0.0
  permission_handler: ^12.0.1
  shared_preferences: ^2.5.3
  confetti: ^0.8.0
  flutter_launcher_icons: ^0.14.4
  url_launcher: ^6.3.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
  
